volumes:
  data:

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=luo
      - POSTGRES_PASSWORD=666666
      - POSTGRES_DB=MicroSer
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql
  myapp:
    image: postgres